### ISSUE TITLE
how to instance hairs, interpolating between alembic 

### ISSUE THREAD

**Issue by MarcTeuberDE** [Unity-Technologies/com.unity.demoteam.hair#51]
Ive brought an alembic with curves from Blender to Unity. It contains strands, based on which, Id like to instance hairs on the head mesh. How can I use the alembic curves as guides and create hairs between them?

**Comment by fuglsang** [comment]
Hi there. The system works somewhat in reverse to what you suggest: It always expects the imported set of curves to be the full groom (not just the guides). And, since full grooms can be rather heavy, the system then also implements a feature to hierarchically compute the X most representative strands based on the full groom. This is the "LOD Clusters" feature exposed in the hair asset inspector. With "LOD Clusters" enabled, building the strand groups in the hair asset will also include the hierarchical clustering step, and the outcome is that you get multiple levels of detail that you can flip/blend between via the "LOD Selection" slider in a hair instance.

**Comment by MarcTeuberDE** [comment]
Thank you so much for replying. That was just what I needed to know!


Am Fr., 10. März 2023 um 14:06 Uhr schrieb Lasse Jon Fuglsang Pedersen <
***@***.***>:
